//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSDLab.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Album()
        {
            this.TransactionDetails = new HashSet<TransactionDetail>();
        }
    
        public int albumId { get; set; }
        public Nullable<int> artistId { get; set; }
        public string albumName { get; set; }
        public string albumImage { get; set; }
        public Nullable<int> albumPrice { get; set; }
        public Nullable<int> albumStock { get; set; }
        public string albumDesc { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Cart Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
    }
}
